# Generated by Django 6.1.1 on 2026-09-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/professores'),
        ),
    ]
