# Generated by Django 6.1 on 2026-09-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_professor_foto'),
        ('estudantes', '0003_delete_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='fotos/cursos')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ManyToManyField(blank=True, to='academico.professor'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='estudante',
            field=models.ManyToManyField(blank=True, to='estudantes.estudante'),
        ),
    ]
