# Generated by Django 6.1.1 on 2026-09-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0002_estudante_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
